#! /bin/bash

THINGS_TO_COPY="\
areas.js \
los.css \
LOS_Data_Sources.pdf \
Instructional_Guide_for_Map_Viewers_01-28-15.pdf \
icons \
index.html \
libs \
splashScreen.html \
"

rsync --delete --exclude **/.git --delete-excluded -av ${THINGS_TO_COPY} html/
